import { app } from 'electron'
import { join } from 'node:path'
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync, rmSync } from 'node:fs'
import type { Conversation, ConversationMeta } from '../shared/types'

function dir(): string {
  const d = join(app.getPath('userData'), 'conversations')
  if (!existsSync(d)) mkdirSync(d, { recursive: true })
  return d
}

function fileFor(id: string): string {
  // ids are generated by us (timestamp-random), safe as filenames.
  return join(dir(), `${id}.json`)
}

export function listConversations(): ConversationMeta[] {
  const metas: ConversationMeta[] = []
  for (const f of readdirSync(dir())) {
    if (!f.endsWith('.json')) continue
    try {
      const c = JSON.parse(readFileSync(join(dir(), f), 'utf8')) as Conversation
      metas.push({
        id: c.id,
        title: c.title,
        model: c.model,
        workspace: c.workspace,
        createdAt: c.createdAt,
        updatedAt: c.updatedAt
      })
    } catch {
      // skip corrupt file
    }
  }
  metas.sort((a, b) => b.updatedAt - a.updatedAt)
  return metas
}

export function getConversation(id: string): Conversation | null {
  const p = fileFor(id)
  if (!existsSync(p)) return null
  try {
    return JSON.parse(readFileSync(p, 'utf8')) as Conversation
  } catch {
    return null
  }
}

export function saveConversation(convo: Conversation): Conversation {
  writeFileSync(fileFor(convo.id), JSON.stringify(convo, null, 2), 'utf8')
  return convo
}

export function deleteConversation(id: string): void {
  const p = fileFor(id)
  if (existsSync(p)) rmSync(p)
}
